language: csharp
solution: CloudflareWorkersKvExplorer.sln
mono: none
dotnet: 2.1.502
before_script:
  - sudo apt install openssh-server
  - sudo apt-get install sshpass
script:
  - dotnet restore
  - dotnet build
  - dotnet publish -c Release
  - export SSHPASS=$DEPLOYMENT_SECRET
  - sshpass -e scp -o StrictHostKeyChecking=no -P 22 -r src/CloudflareWorkersKvExplorer.Website/bin/Release/netcoreapp2.2/publish/* $USER@$SERVER_IP:/var/www/cloudflare-workers-kv-explorer
  - sshpass -e ssh -p 22 $USER@$SERVER_IP sudo supervisorctl restart cloudflare_workers_kv_explorer